INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_BddP6PYo2gs',
      'BddP6PYo2gs',
      'https://www.youtube.com/watch?v=BddP6PYo2gs',
      'https://www.youtube.com/watch?v=BddP6PYo2gs',
      'Kesariya | Arijit Singh, Pritam | Brahmastra',
      'Kesariya',
      'Arijit Singh, Pritam',
      'Brahmastra',
      2022,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/BddP6PYo2gs/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/BddP6PYo2gs',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_K4xLi8IF1FM',
      'K4xLi8IF1FM',
      'https://www.youtube.com/watch?v=K4xLi8IF1FM',
      'https://www.youtube.com/watch?v=K4xLi8IF1FM',
      'Chaleya | Arijit Singh, Shilpa Rao, Anirudh | Jawan',
      'Chaleya',
      'Arijit Singh, Shilpa Rao, Anirudh',
      'Jawan',
      2023,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/K4xLi8IF1FM/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/K4xLi8IF1FM',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_d9MyW72ELq0',
      'd9MyW72ELq0',
      'https://www.youtube.com/watch?v=d9MyW72ELq0',
      'https://www.youtube.com/watch?v=d9MyW72ELq0',
      'Tum Hi Ho | Arijit Singh, Mithoon | Aashiqui 2',
      'Tum Hi Ho',
      'Arijit Singh, Mithoon',
      'Aashiqui 2',
      2013,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/d9MyW72ELq0/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/d9MyW72ELq0',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_kJQP7kiw5Fk',
      'kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'Despacito Bollywood Mix | Luis Fonsi, Indian Fusion | Fusion',
      'Despacito Bollywood Mix',
      'Luis Fonsi, Indian Fusion',
      'Fusion',
      2020,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/kJQP7kiw5Fk',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_T94PHkuydcw',
      'T94PHkuydcw',
      'https://www.youtube.com/watch?v=T94PHkuydcw',
      'https://www.youtube.com/watch?v=T94PHkuydcw',
      'Kun Faya Kun | A.R. Rahman, Javed Ali | Rockstar',
      'Kun Faya Kun',
      'A.R. Rahman, Javed Ali',
      'Rockstar',
      2011,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/T94PHkuydcw/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/T94PHkuydcw',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_gvyUuxdRdR4',
      'gvyUuxdRdR4',
      'https://www.youtube.com/watch?v=gvyUuxdRdR4',
      'https://www.youtube.com/watch?v=gvyUuxdRdR4',
      'Shayad | Arijit Singh, Pritam | Love Aaj Kal',
      'Shayad',
      'Arijit Singh, Pritam',
      'Love Aaj Kal',
      2020,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/gvyUuxdRdR4/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/gvyUuxdRdR4',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_284Ov7ysmfA',
      '284Ov7ysmfA',
      'https://www.youtube.com/watch?v=284Ov7ysmfA',
      'https://www.youtube.com/watch?v=284Ov7ysmfA',
      'Ghungroo | Arijit Singh, Shilpa Rao | War',
      'Ghungroo',
      'Arijit Singh, Shilpa Rao',
      'War',
      2019,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/284Ov7ysmfA/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/284Ov7ysmfA',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_ElZfdU54Cp8',
      'ElZfdU54Cp8',
      'https://www.youtube.com/watch?v=ElZfdU54Cp8',
      'https://www.youtube.com/watch?v=ElZfdU54Cp8',
      'Gerua | Arijit Singh, Antara Mitra | Dilwale',
      'Gerua',
      'Arijit Singh, Antara Mitra',
      'Dilwale',
      2015,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/ElZfdU54Cp8/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/ElZfdU54Cp8',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_JFcgOboQZ08',
      'JFcgOboQZ08',
      'https://www.youtube.com/watch?v=JFcgOboQZ08',
      'https://www.youtube.com/watch?v=JFcgOboQZ08',
      'Kabira | Tochi Raina, Rekha Bhardwaj | Yeh Jawaani Hai Deewani',
      'Kabira',
      'Tochi Raina, Rekha Bhardwaj',
      'Yeh Jawaani Hai Deewani',
      2013,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/JFcgOboQZ08/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/JFcgOboQZ08',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_k4yXQkG2s1E',
      'k4yXQkG2s1E',
      'https://www.youtube.com/watch?v=k4yXQkG2s1E',
      'https://www.youtube.com/watch?v=k4yXQkG2s1E',
      'Subhanallah | Sreeram, Shilpa Rao | Yeh Jawaani Hai Deewani',
      'Subhanallah',
      'Sreeram, Shilpa Rao',
      'Yeh Jawaani Hai Deewani',
      2013,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/k4yXQkG2s1E/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/k4yXQkG2s1E',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_hoNb6HuNmU0',
      'hoNb6HuNmU0',
      'https://www.youtube.com/watch?v=hoNb6HuNmU0',
      'https://www.youtube.com/watch?v=hoNb6HuNmU0',
      'Balam Pichkari | Vishal Dadlani, Shalmali | Yeh Jawaani Hai Deewani',
      'Balam Pichkari',
      'Vishal Dadlani, Shalmali',
      'Yeh Jawaani Hai Deewani',
      2013,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/hoNb6HuNmU0/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/hoNb6HuNmU0',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_YxWlaYCA8MU',
      'YxWlaYCA8MU',
      'https://www.youtube.com/watch?v=YxWlaYCA8MU',
      'https://www.youtube.com/watch?v=YxWlaYCA8MU',
      'Pee Loon | Mohit Chauhan | Once Upon A Time In Mumbaai',
      'Pee Loon',
      'Mohit Chauhan',
      'Once Upon A Time In Mumbaai',
      2010,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/YxWlaYCA8MU/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/YxWlaYCA8MU',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_e-ORhEE9VVg',
      'e-ORhEE9VVg',
      'https://www.youtube.com/watch?v=e-ORhEE9VVg',
      'https://www.youtube.com/watch?v=e-ORhEE9VVg',
      'Matargashti | Mohit Chauhan, A.R. Rahman | Tamasha',
      'Matargashti',
      'Mohit Chauhan, A.R. Rahman',
      'Tamasha',
      2015,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/e-ORhEE9VVg/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/e-ORhEE9VVg',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_sK7riqg2mr4',
      'sK7riqg2mr4',
      'https://www.youtube.com/watch?v=sK7riqg2mr4',
      'https://www.youtube.com/watch?v=sK7riqg2mr4',
      'Agar Tum Saath Ho | Alka Yagnik, Arijit Singh | Tamasha',
      'Agar Tum Saath Ho',
      'Alka Yagnik, Arijit Singh',
      'Tamasha',
      2015,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/sK7riqg2mr4/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/sK7riqg2mr4',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_tLqtnGLfm4Q',
      'tLqtnGLfm4Q',
      'https://www.youtube.com/watch?v=tLqtnGLfm4Q',
      'https://www.youtube.com/watch?v=tLqtnGLfm4Q',
      'Kaun Tujhe | Palak Muchhal, Amaal Mallik | M.S. Dhoni',
      'Kaun Tujhe',
      'Palak Muchhal, Amaal Mallik',
      'M.S. Dhoni',
      2016,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/tLqtnGLfm4Q/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/tLqtnGLfm4Q',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_hcMzwMrr1tE',
      'hcMzwMrr1tE',
      'https://www.youtube.com/watch?v=hcMzwMrr1tE',
      'https://www.youtube.com/watch?v=hcMzwMrr1tE',
      'Besabriyaan | Armaan Malik | M.S. Dhoni',
      'Besabriyaan',
      'Armaan Malik',
      'M.S. Dhoni',
      2016,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/hcMzwMrr1tE/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/hcMzwMrr1tE',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_kJQP7kiw5Fk',
      'kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'Main Rang Sharbaton Ka | Atif Aslam, Chinmayi | Phata Poster Nikhla Hero',
      'Main Rang Sharbaton Ka',
      'Atif Aslam, Chinmayi',
      'Phata Poster Nikhla Hero',
      2013,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/kJQP7kiw5Fk',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_HqUeSjsYLNU',
      'HqUeSjsYLNU',
      'https://www.youtube.com/watch?v=HqUeSjsYLNU',
      'https://www.youtube.com/watch?v=HqUeSjsYLNU',
      'Tu Jaane Na | Atif Aslam, Pritam | Ajab Prem Ki Ghazab Kahani',
      'Tu Jaane Na',
      'Atif Aslam, Pritam',
      'Ajab Prem Ki Ghazab Kahani',
      2009,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/HqUeSjsYLNU/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/HqUeSjsYLNU',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_sCbbMZ-q4-I',
      'sCbbMZ-q4-I',
      'https://www.youtube.com/watch?v=sCbbMZ-q4-I',
      'https://www.youtube.com/watch?v=sCbbMZ-q4-I',
      'Hawayein | Arijit Singh, Pritam | Jab Harry Met Sejal',
      'Hawayein',
      'Arijit Singh, Pritam',
      'Jab Harry Met Sejal',
      2017,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/sCbbMZ-q4-I/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/sCbbMZ-q4-I',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_60ItHLz5WEA',
      '60ItHLz5WEA',
      'https://www.youtube.com/watch?v=60ItHLz5WEA',
      'https://www.youtube.com/watch?v=60ItHLz5WEA',
      'Bullya | Amit Mishra, Shilpa Rao | Ae Dil Hai Mushkil',
      'Bullya',
      'Amit Mishra, Shilpa Rao',
      'Ae Dil Hai Mushkil',
      2016,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/60ItHLz5WEA/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/60ItHLz5WEA',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_bo_efYhYU2A',
      'bo_efYhYU2A',
      'https://www.youtube.com/watch?v=bo_efYhYU2A',
      'https://www.youtube.com/watch?v=bo_efYhYU2A',
      'Swag Se Swagat | Vishal Dadlani, Neha Bhasin | Tiger Zinda Hai',
      'Swag Se Swagat',
      'Vishal Dadlani, Neha Bhasin',
      'Tiger Zinda Hai',
      2017,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/bo_efYhYU2A/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/bo_efYhYU2A',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_qfdShSZZxlg',
      'qfdShSZZxlg',
      'https://www.youtube.com/watch?v=qfdShSZZxlg',
      'https://www.youtube.com/watch?v=qfdShSZZxlg',
      'Ullu Ka Pattha | Arijit Singh, Nikhita Gandhi | Jagga Jasoos',
      'Ullu Ka Pattha',
      'Arijit Singh, Nikhita Gandhi',
      'Jagga Jasoos',
      2017,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/qfdShSZZxlg/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/qfdShSZZxlg',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_dZ0fwJojhrs',
      'dZ0fwJojhrs',
      'https://www.youtube.com/watch?v=dZ0fwJojhrs',
      'https://www.youtube.com/watch?v=dZ0fwJojhrs',
      'Tere Liye | Lata Mangeshkar, Roop Kumar Rathod | Veer-Zaara',
      'Tere Liye',
      'Lata Mangeshkar, Roop Kumar Rathod',
      'Veer-Zaara',
      2004,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/dZ0fwJojhrs/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/dZ0fwJojhrs',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_9bZkp7q19f0',
      '9bZkp7q19f0',
      'https://www.youtube.com/watch?v=9bZkp7q19f0',
      'https://www.youtube.com/watch?v=9bZkp7q19f0',
      'Pee Loon Humsafar | Mohit Chauhan | Once Upon A Time',
      'Pee Loon Humsafar',
      'Mohit Chauhan',
      'Once Upon A Time',
      2010,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/9bZkp7q19f0',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );
INSERT OR REPLACE INTO music_catalog (
      id, youtube_video_id, youtube_url, canonical_url, title, song_name, artist,
      album_or_movie, release_year, language, theme, thumbnail_url, channel_name,
      duration_seconds, embed_url, is_embeddable, youtube_status, playable_status,
      last_checked_at, source, added_by, is_active
    ) VALUES (
      'song_kJQP7kiw5Fk',
      'kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
      'London Thumakda | Labh Janjua, Sonu Kakkar | Queen',
      'London Thumakda',
      'Labh Janjua, Sonu Kakkar',
      'Queen',
      2014,
      'Hindi',
      'BOLLYWOOD',
      'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
      'Official',
      240,
      'https://www.youtube.com/embed/kJQP7kiw5Fk',
      1,
      'AVAILABLE',
      'PLAYABLE',
      datetime('now'),
      'SYSTEM',
      'SUPER_ADMIN',
      1
    );